site_name: High Speed Network
repo_url: https://github.com/makramab/high-speed-network
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: getting_started/quickstart/quickstart.md
  - Assignments:
      - Assignment 1: assignments/assignment-1.md
